services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - default
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  mysql:
    image: mysql:8.0
    container_name: itsapp-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: itsapp
    networks:
      - default
networks:
  default:
    driver: bridge

